# خطاهای سرور MCP جلسات.

from errors.crud import (
    DATABASE_ERROR,
    INVALID_INPUT,
    MEETING_NOT_FOUND,
    MEETING_PARTICIPANT_NOT_FOUND,
    MEETING_SCHEDULE_NOT_FOUND,
    MEETING_SLOT_CONFLICT,
    PERMISSION_DENIED,
    PROJECT_NOT_FOUND,
    QUERY_TIMEOUT,
    USER_NOT_FOUND,
    CrudError,
    DatabaseError,
    InvalidInputError,
    MeetingNotFoundError,
    MeetingParticipantNotFoundError,
    MeetingScheduleNotFoundError,
    MeetingSlotConflictError,
    PermissionDeniedError,
    ProjectNotFoundError,
    QueryTimeoutError,
    UserNotFoundError,
    format_error,
    format_success,
)

__all__ = [
    "DATABASE_ERROR",
    "INVALID_INPUT",
    "MEETING_NOT_FOUND",
    "MEETING_PARTICIPANT_NOT_FOUND",
    "MEETING_SCHEDULE_NOT_FOUND",
    "MEETING_SLOT_CONFLICT",
    "PERMISSION_DENIED",
    "PROJECT_NOT_FOUND",
    "QUERY_TIMEOUT",
    "USER_NOT_FOUND",
    "CrudError",
    "DatabaseError",
    "InvalidInputError",
    "MeetingNotFoundError",
    "MeetingParticipantNotFoundError",
    "MeetingScheduleNotFoundError",
    "MeetingSlotConflictError",
    "PermissionDeniedError",
    "ProjectNotFoundError",
    "QueryTimeoutError",
    "UserNotFoundError",
    "format_error",
    "format_success",
]
