# خطاهای سرور MCP تبدیل گفتار به متن.

from errors.crud import (
    CONFIG_ERROR,
    DATABASE_ERROR,
    EMPTY_TRANSCRIPT,
    INVALID_INPUT,
    PERMISSION_DENIED,
    STT_PROVIDER_ERROR,
    STT_TIMEOUT,
    STT_UNRECOGNIZED,
    ConfigError,
    CrudError,
    DatabaseError,
    EmptyTranscriptError,
    InvalidInputError,
    PermissionDeniedError,
    SttProviderError,
    SttTimeoutError,
    SttUnrecognizedError,
    format_error,
    format_success,
)

__all__ = [
    "CONFIG_ERROR",
    "DATABASE_ERROR",
    "EMPTY_TRANSCRIPT",
    "INVALID_INPUT",
    "PERMISSION_DENIED",
    "STT_PROVIDER_ERROR",
    "STT_TIMEOUT",
    "STT_UNRECOGNIZED",
    "ConfigError",
    "CrudError",
    "DatabaseError",
    "EmptyTranscriptError",
    "InvalidInputError",
    "PermissionDeniedError",
    "SttProviderError",
    "SttTimeoutError",
    "SttUnrecognizedError",
    "format_error",
    "format_success",
]
