"""نشست ورود وب و موبایل.

توکن خام فقط یک‌بار به کلاینت برمی‌گردد. در PostgreSQL هش SHA-256
ذخیره می‌شود. جدول api_sessions اگر نباشد همین‌جا ساخته می‌شود تا
پایگاه فعلی بدون ساخت دوبارهٔ volume هم آماده شود.
"""

from datetime import datetime, timedelta
from hashlib import sha256
import secrets

from pydantic import ValidationError

from auth.hash_password import hash_password, verify_password
from auth.http import ACCOUNT_INACTIVE, INVALID_CREDENTIALS, INVALID_INPUT
from errors.crud import CrudError, DatabaseError, InvalidInputError
from repository.connection import open_connection
from repository.db import run_query
from repository.engine import insert_row_on
from repository.columns import unique_messages_for
from services.audit_log import ACTION_CREATE, record_audit_on

_DUMMY_HASH = (
    "pbkdf2_sha256$150000$"
    + "00" * 16
    + "$"
    + "11" * 32
)

_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS api_sessions (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        token_hash character varying(64) NOT NULL,
        expires_at timestamp without time zone NOT NULL,
        revoked_at timestamp without time zone,
        created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT api_sessions_pkey PRIMARY KEY (id),
        CONSTRAINT api_sessions_token_hash_key UNIQUE (token_hash),
        CONSTRAINT api_sessions_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS api_sessions_user_id_idx
        ON api_sessions (user_id)
    """,
    """
    COMMENT ON TABLE api_sessions IS
        'نشست‌های ورود HTTP برای وب و موبایل. توکن خام ذخیره نمی‌شود.'
    """,
)


class AuthError(CrudError):
    """ورود یا نشست نامعتبر است."""

    def __init__(self, error_code: str, message: str) -> None:
        super().__init__(message)
        self.error_code = error_code


def ensure_api_sessions() -> None:
    """جدول نشست را در صورت نبودن می‌سازد."""
    with _connection() as connection:
        with connection.cursor() as cursor:
            for statement in _SCHEMA_STATEMENTS:
                cursor.execute(statement)
        connection.commit()


def authenticate(username: str, password: str) -> dict:
    """نام کاربری و رمز را با users تطبیق می‌دهد.

    خروجی دیکشنری عمومی کاربر است و password_hash ندارد.
    نام کاربری ناموجود و رمز غلط یک پیام دارند.
    """
    name = (username or "").strip()
    if not name or not password:
        raise AuthError(INVALID_CREDENTIALS, "نام کاربری یا رمز نادرست است")
    row = _fetch_login_user(name)
    stored = row["password_hash"] if row is not None else _DUMMY_HASH
    if not verify_password(password, stored) or row is None:
        raise AuthError(INVALID_CREDENTIALS, "نام کاربری یا رمز نادرست است")
    if not row["is_active"]:
        raise AuthError(ACCOUNT_INACTIVE, "حساب کاربر غیرفعال است")
    return _public_user(row, _role_names(row["id"]))


_REGISTER_FIELDS = ("first_name", "last_name", "username", "password", "phone", "email")
_FIELD_LABELS = {
    "first_name": "نام",
    "last_name": "نام خانوادگی",
    "username": "نام کاربری",
    "password": "رمز",
    "phone": "تلفن",
    "email": "ایمیل",
}
_ADMIN_ROLE = "مدیر کل"
_MEMBER_ROLE = "کاربر"


def register_account(payload: dict) -> dict:
    """کاربر را می‌سازد و نقش پایه می‌دهد.

    اگر هنوز هیچ کاربری نباشد، نقش مدیر کل است تا اولین نفر بتواند
    مدیر سازمان بسازد. حساب‌های بعدی نقش کاربر می‌گیرند و هنوز به
    پروژه‌ای وصل نیستند. سطح دسترسی داخل پروژه را بعداً مدیر پروژه
    با عضویت و نقش پروژه تعیین می‌کند.
    """
    parsed = _parse_registration(payload)

    def work(connection):
        with connection.cursor() as cursor:
            cursor.execute("SELECT pg_advisory_xact_lock(%s)", [804201])  # قفل ثبت‌نام، تا دو درخواست هم‌زمان هر دو مدیر کل نشوند
            cursor.execute("SELECT COUNT(*) FROM users")
            existing = int(cursor.fetchone()[0])
            role_name = _ADMIN_ROLE if existing == 0 else _MEMBER_ROLE
            cursor.execute(
                """
                SELECT id
                FROM roles
                WHERE name = %s
                  AND is_active = true
                """,
                [role_name],
            )
            role = cursor.fetchone()
        if role is None:
            raise AuthError(INVALID_INPUT, "نقش پیش‌فرض ثبت‌نام در پایگاه نیست")
        user_id = insert_row_on(
            connection,
            "users",
            {
                "first_name": parsed["first_name"],
                "last_name": parsed["last_name"],
                "username": parsed["username"],
                "password_hash": hash_password(parsed["password"]),
                "phone": parsed.get("phone"),
                "email": parsed.get("email"),
                "is_active": True,
            },
        )
        assignment_id = insert_row_on(
            connection,
            "user_roles",
            {"user_id": user_id, "role_id": int(role[0]), "is_active": True},
        )
        public = {
            "id": user_id,
            "first_name": parsed["first_name"],
            "last_name": parsed["last_name"],
            "username": parsed["username"],
            "is_active": True,
            "roles": [role_name],
        }
        record_audit_on(
            connection,
            user_id,
            ACTION_CREATE,
            "User",
            user_id,
            None,
            {
                "username": public["username"],
                "first_name": public["first_name"],
                "last_name": public["last_name"],
                "is_active": True,
            },
        )
        record_audit_on(
            connection,
            user_id,
            ACTION_CREATE,
            "UserRole",
            assignment_id,
            None,
            {"user_id": user_id, "role_id": int(role[0]), "is_active": True},
        )
        return public

    messages = {}
    messages.update(unique_messages_for("users"))
    messages.update(unique_messages_for("user_roles"))
    try:
        return run_query(work, messages)
    except AuthError:
        raise
    except InvalidInputError as exc:
        raise AuthError(INVALID_INPUT, exc.message) from exc
    except DatabaseError as exc:
        raise AuthError("DATABASE_ERROR", "ثبت‌نام انجام نشد") from exc


def issue_session(user_id: int, ttl_hours: int) -> dict:
    """یک توکن تازه می‌سازد و هش آن را ذخیره می‌کند."""
    if ttl_hours < 1:
        raise DatabaseError("مدت نشست باید حداقل یک ساعت باشد")
    token = secrets.token_urlsafe(32)
    expires_at = datetime.utcnow() + timedelta(hours=ttl_hours)
    with _connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO api_sessions (user_id, token_hash, expires_at)
                VALUES (%s, %s, %s)
                """,
                [user_id, _hash_token(token), expires_at],
            )
        connection.commit()
    return {
        "access_token": token,
        "token_type": "Bearer",
        "expires_in": ttl_hours * 3600,
        "expires_at": expires_at.isoformat(timespec="seconds"),
    }


def user_for_token(token: str) -> dict | None:
    """اگر توکن معتبر و لغونشده و منقضی‌نشده باشد کاربر را برمی‌گرداند."""
    if not token:
        return None
    with _connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT u.id, u.first_name, u.last_name, u.username, u.is_active,
                       s.expires_at, s.revoked_at
                FROM api_sessions s
                JOIN users u ON u.id = s.user_id
                WHERE s.token_hash = %s
                """,
                [_hash_token(token)],
            )
            row = cursor.fetchone()
        connection.commit()
    if row is None or row[6] is not None or row[5] <= datetime.utcnow():
        return None
    if not row[4]:
        return None
    return _public_user(
        {
            "id": row[0],
            "first_name": row[1],
            "last_name": row[2],
            "username": row[3],
            "is_active": row[4],
        },
        _role_names(row[0]),
    )


def revoke_token(token: str) -> None:
    """نشست همین توکن را می‌بندد. توکن ناشناس خطا نمی‌دهد."""
    if not token:
        return
    with _connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE api_sessions
                SET revoked_at = CURRENT_TIMESTAMP
                WHERE token_hash = %s
                  AND revoked_at IS NULL
                """,
                [_hash_token(token)],
            )
        connection.commit()


def _hash_token(token: str) -> str:
    return sha256(token.encode("utf-8")).hexdigest()


def _fetch_login_user(username: str):
    with _connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT id, first_name, last_name, username, password_hash, is_active
                FROM users
                WHERE username = %s
                """,
                [username],
            )
            row = cursor.fetchone()
        connection.commit()
    if row is None:
        return None
    return {
        "id": row[0],
        "first_name": row[1],
        "last_name": row[2],
        "username": row[3],
        "password_hash": row[4],
        "is_active": row[5],
    }


def _public_user(row: dict, roles: list[str] | None = None) -> dict:
    return {
        "id": row["id"],
        "first_name": row["first_name"],
        "last_name": row["last_name"],
        "username": row["username"],
        "is_active": row["is_active"],
        "roles": list(roles or []),
    }


def _parse_registration(payload: dict) -> dict:
    from schemas.crud.user import CreateUserInput

    if not isinstance(payload, dict):
        raise AuthError(INVALID_INPUT, "بدنه باید یک شیء JSON باشد")
    fields = {}
    for key in _REGISTER_FIELDS:
        value = payload.get(key)
        if value is None or value == "":
            continue
        fields[key] = value
    try:
        parsed = CreateUserInput(**fields).model_dump()
    except ValidationError as exc:
        raise AuthError(INVALID_INPUT, _input_message(exc)) from exc
    parsed["is_active"] = True
    return parsed


def _input_message(exc: ValidationError) -> str:
    error = exc.errors()[0]
    loc = error.get("loc") or ()
    field = str(loc[-1]) if loc else ""
    label = _FIELD_LABELS.get(field, "ورودی")
    kind = str(error.get("type") or "")
    custom = str(error.get("msg") or "")
    if field == "password" and kind == "string_too_short":
        return "رمز باید حداقل ۸ نویسه باشد"
    if kind == "string_too_long":
        return f"{label} طولانی است"
    if kind in {"missing", "string_too_short"} or custom == "نمی‌تواند خالی باشد":
        return f"{label} لازم است"
    if "ایمیل" in custom:
        return "قالب ایمیل معتبر نیست"
    if any("\u0600" <= char <= "\u06ff" for char in custom):
        return custom
    return f"{label} نامعتبر است"


def _role_names(user_id: int) -> list[str]:
    with _connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT r.name
                FROM user_roles ur
                JOIN roles r ON r.id = ur.role_id
                WHERE ur.user_id = %s
                  AND ur.is_active = true
                  AND r.is_active = true
                ORDER BY r.id
                """,
                [user_id],
            )
            names = [row[0] for row in cursor.fetchall()]
        connection.commit()
    return names


class _connection:
    """اتصال کوتاه و بسته‌شونده برای نشست."""

    def __enter__(self):
        self._connection = open_connection()
        return self._connection

    def __exit__(self, exc_type, exc, traceback):
        if exc_type is not None:
            self._connection.rollback()
        self._connection.close()
        return False
