-- مهاجرت ماژول جلسات برای پایگاه‌هایی که قبلاً 001_schema.sql قدیمی اجرا شده.
-- روی نصب تازه لازم نیست (همه چیز در 001_schema.sql هست).

BEGIN;

-- گسترش content_attachments برای پیوست به جلسه؛ اگر جدول هنوز نباشد رد می‌شود.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'content_attachments'
    ) THEN
        ALTER TABLE content_attachments
            DROP CONSTRAINT IF EXISTS content_attachments_attachable_type_check;
        ALTER TABLE content_attachments
            ADD CONSTRAINT content_attachments_attachable_type_check CHECK (
                attachable_type IN (
                    'message',
                    'notification',
                    'task_follow_up',
                    'reminder',
                    'report',
                    'idea_experience',
                    'meeting'
                )
            );
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS meeting_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT meeting_types_pkey PRIMARY KEY (id),
    CONSTRAINT meeting_types_name_key UNIQUE (name),
    CONSTRAINT meeting_types_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE meeting_types IS
    'نوع جلسه: تیم، مذاکره خارجی، حقوقی، مذاکره مدیران و...';

CREATE TABLE IF NOT EXISTS meeting_statuses (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT meeting_statuses_pkey PRIMARY KEY (id),
    CONSTRAINT meeting_statuses_name_key UNIQUE (name),
    CONSTRAINT meeting_statuses_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE meeting_statuses IS
    'وضعیت جلسه: برنامه‌ریزی شده، برگزار شده، ضبط شده، همگام‌سازی شده و...';

CREATE TABLE IF NOT EXISTS meeting_schedules (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    project_id integer,
    meeting_type_id integer NOT NULL,
    day_of_week smallint NOT NULL,
    start_time time without time zone NOT NULL,
    duration_minutes integer NOT NULL DEFAULT 60,
    is_active boolean NOT NULL DEFAULT true,
    effective_from date NOT NULL DEFAULT CURRENT_DATE,
    effective_until date,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT meeting_schedules_pkey PRIMARY KEY (id),
    CONSTRAINT meeting_schedules_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT meeting_schedules_project_id_fkey
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT meeting_schedules_meeting_type_id_fkey
        FOREIGN KEY (meeting_type_id) REFERENCES meeting_types(id) ON DELETE RESTRICT,
    CONSTRAINT meeting_schedules_day_of_week_check CHECK (day_of_week BETWEEN 0 AND 6),
    CONSTRAINT meeting_schedules_duration_check CHECK (duration_minutes > 0),
    CONSTRAINT meeting_schedules_dates_check CHECK (
        effective_until IS NULL OR effective_until >= effective_from
    )
);

COMMENT ON TABLE meeting_schedules IS
    'الگوی تکرار جلسات مدیر؛ ۰=شنبه تا ۶=جمعه. project_id خالی = الگوی شخصی.';

COMMENT ON COLUMN meeting_schedules.day_of_week IS
    '۰=شنبه، ۱=یکشنبه، ۲=دوشنبه، ۳=سه‌شنبه، ۴=چهارشنبه، ۵=پنجشنبه، ۶=جمعه';

CREATE INDEX IF NOT EXISTS meeting_schedules_user_project_active_idx
    ON meeting_schedules (user_id, project_id)
    WHERE is_active;

CREATE TABLE IF NOT EXISTS meetings (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id integer,
    manager_user_id integer NOT NULL,
    schedule_id integer,
    meeting_type_id integer NOT NULL,
    status_id integer NOT NULL,
    visibility character varying(20) NOT NULL DEFAULT 'PRIVATE',
    title character varying(200) NOT NULL,
    scheduled_at timestamp without time zone NOT NULL,
    scheduled_end_at timestamp without time zone NOT NULL,
    duration_minutes integer NOT NULL DEFAULT 60,
    location text,
    held_at timestamp without time zone,
    ended_at timestamp without time zone,
    content_id integer,
    sync_status character varying(20) NOT NULL DEFAULT 'NOT_SYNCED',
    synced_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT meetings_pkey PRIMARY KEY (id),
    CONSTRAINT meetings_project_id_fkey
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT,
    CONSTRAINT meetings_manager_user_id_fkey
        FOREIGN KEY (manager_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT meetings_schedule_id_fkey
        FOREIGN KEY (schedule_id) REFERENCES meeting_schedules(id) ON DELETE SET NULL,
    CONSTRAINT meetings_meeting_type_id_fkey
        FOREIGN KEY (meeting_type_id) REFERENCES meeting_types(id) ON DELETE RESTRICT,
    CONSTRAINT meetings_status_id_fkey
        FOREIGN KEY (status_id) REFERENCES meeting_statuses(id) ON DELETE RESTRICT,
    CONSTRAINT meetings_title_not_empty CHECK (btrim(title) <> ''),
    CONSTRAINT meetings_duration_check CHECK (duration_minutes > 0),
    CONSTRAINT meetings_schedule_window_check CHECK (scheduled_end_at > scheduled_at),
    CONSTRAINT meetings_actual_times_check CHECK (
        ended_at IS NULL OR held_at IS NULL OR ended_at >= held_at
    ),
    CONSTRAINT meetings_visibility_check CHECK (
        visibility IN ('PRIVATE', 'RESTRICTED', 'PROJECT')
    ),
    CONSTRAINT meetings_sync_status_check CHECK (
        sync_status IN ('NOT_SYNCED', 'PARTIAL', 'SYNCED')
    )
);

COMMENT ON TABLE meetings IS
    'نمونهٔ مشخص یک جلسه. project_id خالی = جلسه شخصی/مذاکره مدیران.';

COMMENT ON COLUMN meetings.visibility IS
    'PRIVATE: فقط مدیر و participants؛ RESTRICTED: محدود؛ PROJECT: قابل مشاهده در پروژه.';

COMMENT ON COLUMN meetings.content_id IS
    'ضبط یا یادداشت اصلی جلسه (صوت/متن) از جدول contents.';

COMMENT ON COLUMN meetings.scheduled_end_at IS
    'پایان برنامه‌ریزی‌شده؛ برای چیدن چند جلسه در یک روز و تشخیص تداخل.';

COMMENT ON COLUMN meetings.ended_at IS
    'پایان واقعی جلسه پس از برگزاری؛ held_at زمان شروع واقعی است.';

CREATE INDEX IF NOT EXISTS meetings_manager_scheduled_idx
    ON meetings (manager_user_id, scheduled_at DESC);
CREATE INDEX IF NOT EXISTS meetings_manager_time_range_idx
    ON meetings (manager_user_id, scheduled_at, scheduled_end_at);
CREATE INDEX IF NOT EXISTS meetings_project_scheduled_idx
    ON meetings (project_id, scheduled_at DESC)
    WHERE project_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS meetings_status_scheduled_idx
    ON meetings (status_id, scheduled_at);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'contents'
    ) THEN
        ALTER TABLE meetings
            DROP CONSTRAINT IF EXISTS meetings_content_id_fkey;
        ALTER TABLE meetings
            ADD CONSTRAINT meetings_content_id_fkey
            FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS meeting_participants (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    meeting_id integer NOT NULL,
    user_id integer,
    external_contact_id integer,
    role character varying(50),
    CONSTRAINT meeting_participants_pkey PRIMARY KEY (id),
    CONSTRAINT meeting_participants_meeting_id_fkey
        FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    CONSTRAINT meeting_participants_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT meeting_participants_external_contact_id_fkey
        FOREIGN KEY (external_contact_id) REFERENCES external_contacts(id) ON DELETE CASCADE,
    CONSTRAINT meeting_participants_one_target CHECK (
        (user_id IS NOT NULL AND external_contact_id IS NULL)
        OR (user_id IS NULL AND external_contact_id IS NOT NULL)
    )
);

COMMENT ON TABLE meeting_participants IS
    'شرکت‌کننده جلسه: عضو سامانه یا مخاطب خارجی؛ نه هر دو.';

CREATE UNIQUE INDEX IF NOT EXISTS meeting_participants_meeting_user_idx
    ON meeting_participants (meeting_id, user_id)
    WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS meeting_participants_meeting_external_idx
    ON meeting_participants (meeting_id, external_contact_id)
    WHERE external_contact_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS meeting_participants_meeting_id_idx
    ON meeting_participants (meeting_id);

CREATE TABLE IF NOT EXISTS meeting_sync_items (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    meeting_id integer NOT NULL,
    report_id integer,
    task_id integer,
    idea_experience_id integer,
    message_id integer,
    created_by_user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT meeting_sync_items_pkey PRIMARY KEY (id),
    CONSTRAINT meeting_sync_items_meeting_id_fkey
        FOREIGN KEY (meeting_id) REFERENCES meetings(id) ON DELETE CASCADE,
    CONSTRAINT meeting_sync_items_report_id_fkey
        FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE,
    CONSTRAINT meeting_sync_items_task_id_fkey
        FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT meeting_sync_items_idea_experience_id_fkey
        FOREIGN KEY (idea_experience_id) REFERENCES ideas_experiences(id) ON DELETE CASCADE,
    CONSTRAINT meeting_sync_items_message_id_fkey
        FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
    CONSTRAINT meeting_sync_items_created_by_user_id_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT meeting_sync_items_one_target CHECK (
        (
            (report_id IS NOT NULL)::integer
            + (task_id IS NOT NULL)::integer
            + (idea_experience_id IS NOT NULL)::integer
            + (message_id IS NOT NULL)::integer
        ) = 1
    )
);

COMMENT ON TABLE meeting_sync_items IS
    'ردیابی خروجی sync جلسه به گزارش، وظیفه، تصمیم (ایده/تجربه) یا پیام.';

CREATE INDEX IF NOT EXISTS meeting_sync_items_meeting_id_idx
    ON meeting_sync_items (meeting_id);

COMMIT;
