-- برای پایگاه‌هایی که قبلاً با 001_schema.sql (بدون importance) ساخته شده‌اند.
-- روی نصب تازه اجرا نکنید؛ 001_schema.sql از قبل importance_id را دارد.

BEGIN;

CREATE TABLE IF NOT EXISTS task_importances (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    level integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT task_importances_pkey PRIMARY KEY (id),
    CONSTRAINT task_importances_name_key UNIQUE (name),
    CONSTRAINT task_importances_level_key UNIQUE (level),
    CONSTRAINT task_importances_name_not_empty CHECK (btrim(name) <> ''),
    CONSTRAINT task_importances_level_check CHECK (level >= 1)
);

COMMENT ON TABLE task_importances IS
    'اهمیت استراتژیک تسک: چقدر روی هدف و نتیجه پروژه اثر دارد؛ جدا از اولویت (فوریت).';

INSERT INTO task_importances (name, level, is_active) VALUES
    ('کم', 1, true),
    ('متوسط', 2, true),
    ('زیاد', 3, true),
    ('حیاتی', 4, true)
ON CONFLICT (name) DO NOTHING;

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS importance_id integer;

UPDATE tasks
SET importance_id = (
    SELECT id FROM task_importances WHERE name = 'متوسط' LIMIT 1
)
WHERE importance_id IS NULL;

ALTER TABLE tasks ALTER COLUMN importance_id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'tasks_importance_id_fkey'
    ) THEN
        ALTER TABLE tasks
            ADD CONSTRAINT tasks_importance_id_fkey
            FOREIGN KEY (importance_id) REFERENCES task_importances(id) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS tasks_project_importance_idx ON tasks (project_id, importance_id);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS importance_percent smallint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'tasks_importance_percent_check'
    ) THEN
        ALTER TABLE tasks
            ADD CONSTRAINT tasks_importance_percent_check CHECK (
                importance_percent IS NULL
                OR (importance_percent >= 0 AND importance_percent <= 100)
            );
    END IF;
END $$;

COMMENT ON COLUMN tasks.importance_percent IS
    'درصد اهمیت اختیاری (۰ تا ۱۰۰). مکمل importance_id؛ خالی یعنی فقط سطح دسته‌بندی‌شده کافی است.';

CREATE INDEX IF NOT EXISTS tasks_importance_percent_idx
    ON tasks (project_id, importance_percent DESC NULLS LAST)
    WHERE importance_percent IS NOT NULL;

COMMIT;
