-- نشست ورود HTTP برای وب و موبایل.
-- توکن خام ذخیره نمی‌شود؛ فقط هش SHA-256.
-- IF NOT EXISTS تا اجرای دوباره بی‌خطر باشد.
-- سرور API همین جدول را اگر نباشد خودش هم می‌سازد.

BEGIN;

CREATE TABLE IF NOT EXISTS api_sessions (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    revoked_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT api_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT api_sessions_token_hash_key UNIQUE (token_hash),
    CONSTRAINT api_sessions_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS api_sessions_user_id_idx ON api_sessions (user_id);

COMMENT ON TABLE api_sessions IS
    'نشست‌های ورود HTTP برای وب و موبایل. توکن خام ذخیره نمی‌شود.';

COMMIT;
