-- جزئیات و زیرکارهای Task (چک‌لیست پلکانی) برای پایگاه‌های موجود.

BEGIN;

CREATE TABLE IF NOT EXISTS task_items (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    task_id integer NOT NULL,
    parent_item_id integer,
    title character varying(200) NOT NULL,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    start_date date,
    end_date date,
    is_completed boolean NOT NULL DEFAULT false,
    completed_at timestamp without time zone,
    completed_by_user_id integer,
    created_by_user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT task_items_pkey PRIMARY KEY (id),
    CONSTRAINT task_items_task_id_fkey
        FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT task_items_parent_item_id_fkey
        FOREIGN KEY (parent_item_id) REFERENCES task_items(id) ON DELETE CASCADE,
    CONSTRAINT task_items_completed_by_user_id_fkey
        FOREIGN KEY (completed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT task_items_created_by_user_id_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT task_items_title_not_empty CHECK (btrim(title) <> ''),
    CONSTRAINT task_items_sort_order_check CHECK (sort_order >= 0),
    CONSTRAINT task_items_dates_check CHECK (
        end_date IS NULL OR start_date IS NULL OR end_date >= start_date
    ),
    CONSTRAINT task_items_completion_check CHECK (
        (is_completed = false AND completed_at IS NULL AND completed_by_user_id IS NULL)
        OR (is_completed = true AND completed_at IS NOT NULL)
    )
);

COMMENT ON TABLE task_items IS
    'جزئیات و زیرکارهای یک Task: تقسیم پلکانی، تیک زدن. فقط assigned_to_user_id می‌تواند بسازد/ویرایش/تیک بزند.';

COMMENT ON COLUMN task_items.parent_item_id IS
    'برای زیرمرحله؛ خالی یعنی ردیف سطح اول زیر همان Task.';

COMMENT ON COLUMN task_items.sort_order IS
    'ترتیب نمایش در همان سطح (کنار خواهرها با یک parent_item_id).';

CREATE INDEX IF NOT EXISTS task_items_task_sort_idx
    ON task_items (task_id, parent_item_id, sort_order, id);
CREATE INDEX IF NOT EXISTS task_items_task_open_idx
    ON task_items (task_id, is_completed)
    WHERE is_completed = false;
CREATE INDEX IF NOT EXISTS task_items_end_date_idx
    ON task_items (end_date)
    WHERE end_date IS NOT NULL AND is_completed = false;

COMMIT;
