-- مستندات پروژه + سیستم یکپارچه محتوا (متن/صوت/تصویر/فایل)

BEGIN;

CREATE TABLE IF NOT EXISTS content_kinds (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT content_kinds_pkey PRIMARY KEY (id),
    CONSTRAINT content_kinds_code_key UNIQUE (code),
    CONSTRAINT content_kinds_name_key UNIQUE (name),
    CONSTRAINT content_kinds_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT content_kinds_name_not_empty CHECK (btrim(name) <> ''),
    CONSTRAINT content_kinds_code_check CHECK (code IN ('TEXT', 'VOICE', 'IMAGE', 'FILE'))
);

INSERT INTO content_kinds (code, name, description, is_active) VALUES
    ('TEXT', 'متن', 'متن ساده یا caption', true),
    ('VOICE', 'صوت', 'پیام صوتی / ویس', true),
    ('IMAGE', 'تصویر', 'عکس', true),
    ('FILE', 'فایل', 'سند، PDF، Excel و...', true)
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS media_files (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    storage_key character varying(500) NOT NULL,
    original_filename character varying(255) NOT NULL,
    mime_type character varying(120) NOT NULL,
    file_size_bytes bigint NOT NULL,
    duration_seconds integer,
    uploaded_by_user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT media_files_pkey PRIMARY KEY (id),
    CONSTRAINT media_files_storage_key_key UNIQUE (storage_key),
    CONSTRAINT media_files_uploaded_by_user_id_fkey
        FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT media_files_storage_key_not_empty CHECK (btrim(storage_key) <> ''),
    CONSTRAINT media_files_original_filename_not_empty CHECK (btrim(original_filename) <> ''),
    CONSTRAINT media_files_mime_type_not_empty CHECK (btrim(mime_type) <> ''),
    CONSTRAINT media_files_file_size_bytes_check CHECK (file_size_bytes > 0),
    CONSTRAINT media_files_duration_seconds_check CHECK (
        duration_seconds IS NULL OR duration_seconds >= 0
    )
);

CREATE TABLE IF NOT EXISTS contents (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content_kind_id integer NOT NULL,
    text_body text,
    media_file_id integer,
    created_by_user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contents_pkey PRIMARY KEY (id),
    CONSTRAINT contents_content_kind_id_fkey
        FOREIGN KEY (content_kind_id) REFERENCES content_kinds(id) ON DELETE RESTRICT,
    CONSTRAINT contents_media_file_id_fkey
        FOREIGN KEY (media_file_id) REFERENCES media_files(id) ON DELETE RESTRICT,
    CONSTRAINT contents_created_by_user_id_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE OR REPLACE FUNCTION contents_validate_kind()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_code character varying(20);
BEGIN
    SELECT code INTO v_code
    FROM content_kinds
    WHERE id = NEW.content_kind_id;

    IF v_code = 'TEXT' THEN
        IF btrim(coalesce(NEW.text_body, '')) = '' THEN
            RAISE EXCEPTION 'TEXT content requires text_body';
        END IF;
        IF NEW.media_file_id IS NOT NULL THEN
            RAISE EXCEPTION 'TEXT content must not have media_file_id';
        END IF;
    ELSIF v_code IN ('VOICE', 'IMAGE', 'FILE') THEN
        IF NEW.media_file_id IS NULL THEN
            RAISE EXCEPTION '% content requires media_file_id', v_code;
        END IF;
    ELSE
        RAISE EXCEPTION 'Unknown content kind code: %', v_code;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS contents_validate_kind_trg ON contents;

CREATE TRIGGER contents_validate_kind_trg
    BEFORE INSERT OR UPDATE ON contents
    FOR EACH ROW
    EXECUTE FUNCTION contents_validate_kind();

CREATE TABLE IF NOT EXISTS project_documents (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id integer NOT NULL,
    content_id integer NOT NULL,
    title character varying(200),
    description text,
    created_by_user_id integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_documents_pkey PRIMARY KEY (id),
    CONSTRAINT project_documents_project_id_fkey
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT project_documents_content_id_fkey
        FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE RESTRICT,
    CONSTRAINT project_documents_created_by_user_id_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT project_documents_content_id_key UNIQUE (content_id)
);

CREATE TABLE IF NOT EXISTS content_attachments (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    content_id integer NOT NULL,
    attachable_type character varying(40) NOT NULL,
    attachable_id integer NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT content_attachments_pkey PRIMARY KEY (id),
    CONSTRAINT content_attachments_content_id_fkey
        FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE CASCADE,
    CONSTRAINT content_attachments_content_attachable_key
        UNIQUE (content_id, attachable_type, attachable_id),
    CONSTRAINT content_attachments_sort_order_check CHECK (sort_order >= 0),
    CONSTRAINT content_attachments_attachable_type_check CHECK (
        attachable_type IN (
            'message',
            'notification',
            'task_follow_up',
            'reminder',
            'report',
            'idea_experience'
        )
    )
);

CREATE INDEX IF NOT EXISTS media_files_uploaded_by_idx
    ON media_files (uploaded_by_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS contents_kind_created_idx
    ON contents (content_kind_id, created_at DESC);
CREATE INDEX IF NOT EXISTS project_documents_project_created_idx
    ON project_documents (project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS content_attachments_target_idx
    ON content_attachments (attachable_type, attachable_id, sort_order, id);

-- messages
ALTER TABLE messages ADD COLUMN IF NOT EXISTS content_id integer;
ALTER TABLE messages ALTER COLUMN text DROP NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'messages_text_not_empty'
    ) THEN
        ALTER TABLE messages DROP CONSTRAINT messages_text_not_empty;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'messages_content_id_fkey'
    ) THEN
        ALTER TABLE messages
            ADD CONSTRAINT messages_content_id_fkey
            FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'messages_body_check'
    ) THEN
        ALTER TABLE messages
            ADD CONSTRAINT messages_body_check CHECK (
                content_id IS NOT NULL OR btrim(coalesce(text, '')) <> ''
            );
    END IF;
END $$;

-- task_follow_ups
ALTER TABLE task_follow_ups ADD COLUMN IF NOT EXISTS content_id integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'task_follow_ups_content_id_fkey'
    ) THEN
        ALTER TABLE task_follow_ups
            ADD CONSTRAINT task_follow_ups_content_id_fkey
            FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'task_follow_ups_body_check'
    ) THEN
        ALTER TABLE task_follow_ups
            ADD CONSTRAINT task_follow_ups_body_check CHECK (
                content_id IS NOT NULL OR btrim(coalesce(note, '')) <> ''
            );
    END IF;
END $$;

-- reports
ALTER TABLE reports ADD COLUMN IF NOT EXISTS content_id integer;
ALTER TABLE reports ALTER COLUMN body DROP NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reports_body_not_empty'
    ) THEN
        ALTER TABLE reports DROP CONSTRAINT reports_body_not_empty;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reports_content_id_fkey'
    ) THEN
        ALTER TABLE reports
            ADD CONSTRAINT reports_content_id_fkey
            FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reports_body_check'
    ) THEN
        ALTER TABLE reports
            ADD CONSTRAINT reports_body_check CHECK (
                content_id IS NOT NULL OR btrim(coalesce(body, '')) <> ''
            );
    END IF;
END $$;

-- ideas_experiences
ALTER TABLE ideas_experiences ADD COLUMN IF NOT EXISTS content_id integer;
ALTER TABLE ideas_experiences ALTER COLUMN description DROP NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ideas_experiences_description_not_empty'
    ) THEN
        ALTER TABLE ideas_experiences DROP CONSTRAINT ideas_experiences_description_not_empty;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ideas_experiences_content_id_fkey'
    ) THEN
        ALTER TABLE ideas_experiences
            ADD CONSTRAINT ideas_experiences_content_id_fkey
            FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ideas_experiences_body_check'
    ) THEN
        ALTER TABLE ideas_experiences
            ADD CONSTRAINT ideas_experiences_body_check CHECK (
                content_id IS NOT NULL OR btrim(coalesce(description, '')) <> ''
            );
    END IF;
END $$;

-- reminders
ALTER TABLE reminders ADD COLUMN IF NOT EXISTS content_id integer;
ALTER TABLE reminders ALTER COLUMN message_template DROP NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reminders_template_not_empty'
    ) THEN
        ALTER TABLE reminders DROP CONSTRAINT reminders_template_not_empty;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reminders_content_id_fkey'
    ) THEN
        ALTER TABLE reminders
            ADD CONSTRAINT reminders_content_id_fkey
            FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reminders_body_check'
    ) THEN
        ALTER TABLE reminders
            ADD CONSTRAINT reminders_body_check CHECK (
                content_id IS NOT NULL OR btrim(coalesce(message_template, '')) <> ''
            );
    END IF;
END $$;

-- notifications
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS content_id integer;
ALTER TABLE notifications ALTER COLUMN message DROP NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'notifications_message_not_empty'
    ) THEN
        ALTER TABLE notifications DROP CONSTRAINT notifications_message_not_empty;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'notifications_content_id_fkey'
    ) THEN
        ALTER TABLE notifications
            ADD CONSTRAINT notifications_content_id_fkey
            FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'notifications_body_check'
    ) THEN
        ALTER TABLE notifications
            ADD CONSTRAINT notifications_body_check CHECK (
                content_id IS NOT NULL OR btrim(coalesce(message, '')) <> ''
            );
    END IF;
END $$;

COMMIT;
