-- لایه تحلیل متن روی گزارش، جلسه و پیام.
-- جداول عملیاتی (reports / meetings / messages / tasks / ...) را تغییر نمی‌دهد.
-- نصب تازه: همین جدول‌ها در 001_schema.sql هستند؛ seed در 002_seed.sql.
-- پایگاه موجود: همین فایل را اجرا کنید (CREATE IF NOT EXISTS + seed).

BEGIN;

-- =============================================================================
-- Lookupهای توسعه‌پذیر (مثل report_types): ردیف جدید = نوع جدید، بدون ALTER
-- =============================================================================

CREATE TABLE IF NOT EXISTS analysis_source_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT analysis_source_types_pkey PRIMARY KEY (id),
    CONSTRAINT analysis_source_types_code_key UNIQUE (code),
    CONSTRAINT analysis_source_types_name_key UNIQUE (name),
    CONSTRAINT analysis_source_types_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT analysis_source_types_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE analysis_source_types IS
    'نوع منبع متن خام که تحلیل روی آن اجرا می‌شود؛ خود منبع در جدول عملیاتی می‌ماند.';

CREATE TABLE IF NOT EXISTS discourse_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT discourse_types_pkey PRIMARY KEY (id),
    CONSTRAINT discourse_types_code_key UNIQUE (code),
    CONSTRAINT discourse_types_name_key UNIQUE (name),
    CONSTRAINT discourse_types_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT discourse_types_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE discourse_types IS
    'ژانر متن استخراج‌شده (گزارش، رخداد، درخواست، ...). با نوع رکورد عملیاتی فرق دارد.';

CREATE TABLE IF NOT EXISTS intents (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT intents_pkey PRIMARY KEY (id),
    CONSTRAINT intents_code_key UNIQUE (code),
    CONSTRAINT intents_name_key UNIQUE (name),
    CONSTRAINT intents_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT intents_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE intents IS
    'نیت گوینده از متن: اطلاع‌رسانی، درخواست اقدام، گزارش مشکل و...';

CREATE TABLE IF NOT EXISTS entity_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT entity_types_pkey PRIMARY KEY (id),
    CONSTRAINT entity_types_code_key UNIQUE (code),
    CONSTRAINT entity_types_name_key UNIQUE (name),
    CONSTRAINT entity_types_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT entity_types_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE entity_types IS
    'نوع موجودیت استخراج‌شده: فرد، واحد، سازمان، مکان، شیء، پروژه، تسک، زمان، نقش.';

CREATE TABLE IF NOT EXISTS entity_statuses (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT entity_statuses_pkey PRIMARY KEY (id),
    CONSTRAINT entity_statuses_code_key UNIQUE (code),
    CONSTRAINT entity_statuses_name_key UNIQUE (name),
    CONSTRAINT entity_statuses_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT entity_statuses_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE entity_statuses IS
    'وضعیت موجودیت canonical: پیشنهادی مدل، تأییدشده، ردشده.';

CREATE TABLE IF NOT EXISTS relation_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT relation_types_pkey PRIMARY KEY (id),
    CONSTRAINT relation_types_code_key UNIQUE (code),
    CONSTRAINT relation_types_name_key UNIQUE (name),
    CONSTRAINT relation_types_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT relation_types_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE relation_types IS
    'نوع رابطه معنایی بین دو موجودیت: علت، مسئولیت، پیامد، وابستگی، تناقض و...';

CREATE TABLE IF NOT EXISTS polarities (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT polarities_pkey PRIMARY KEY (id),
    CONSTRAINT polarities_code_key UNIQUE (code),
    CONSTRAINT polarities_name_key UNIQUE (name),
    CONSTRAINT polarities_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT polarities_name_not_empty CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS emotions (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT emotions_pkey PRIMARY KEY (id),
    CONSTRAINT emotions_code_key UNIQUE (code),
    CONSTRAINT emotions_name_key UNIQUE (name),
    CONSTRAINT emotions_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT emotions_name_not_empty CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS intensity_levels (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    level integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT intensity_levels_pkey PRIMARY KEY (id),
    CONSTRAINT intensity_levels_code_key UNIQUE (code),
    CONSTRAINT intensity_levels_name_key UNIQUE (name),
    CONSTRAINT intensity_levels_level_key UNIQUE (level),
    CONSTRAINT intensity_levels_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT intensity_levels_name_not_empty CHECK (btrim(name) <> ''),
    CONSTRAINT intensity_levels_level_check CHECK (level >= 1)
);

CREATE TABLE IF NOT EXISTS severity_levels (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    level integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT severity_levels_pkey PRIMARY KEY (id),
    CONSTRAINT severity_levels_code_key UNIQUE (code),
    CONSTRAINT severity_levels_name_key UNIQUE (name),
    CONSTRAINT severity_levels_level_key UNIQUE (level),
    CONSTRAINT severity_levels_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT severity_levels_name_not_empty CHECK (btrim(name) <> ''),
    CONSTRAINT severity_levels_level_check CHECK (level >= 1)
);

COMMENT ON TABLE severity_levels IS
    'شدت اثر مسئله؛ جدا از اهمیت (task_importances) و فوریت (task_priorities).';

CREATE TABLE IF NOT EXISTS issue_statuses (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT issue_statuses_pkey PRIMARY KEY (id),
    CONSTRAINT issue_statuses_code_key UNIQUE (code),
    CONSTRAINT issue_statuses_name_key UNIQUE (name),
    CONSTRAINT issue_statuses_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT issue_statuses_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE issue_statuses IS
    'وضعیت مسئله هوشمند؛ با task_statuses یکی نیست.';

CREATE TABLE IF NOT EXISTS cause_levels (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    level integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT cause_levels_pkey PRIMARY KEY (id),
    CONSTRAINT cause_levels_code_key UNIQUE (code),
    CONSTRAINT cause_levels_name_key UNIQUE (name),
    CONSTRAINT cause_levels_level_key UNIQUE (level),
    CONSTRAINT cause_levels_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT cause_levels_name_not_empty CHECK (btrim(name) <> ''),
    CONSTRAINT cause_levels_level_check CHECK (level >= 1)
);

COMMENT ON TABLE cause_levels IS
    'عمق علت: علت مستقیم یا ریشه. زنجیره با چند ردیف issue_causes ساخته می‌شود.';

CREATE TABLE IF NOT EXISTS issue_entity_roles (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT issue_entity_roles_pkey PRIMARY KEY (id),
    CONSTRAINT issue_entity_roles_code_key UNIQUE (code),
    CONSTRAINT issue_entity_roles_name_key UNIQUE (name),
    CONSTRAINT issue_entity_roles_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT issue_entity_roles_name_not_empty CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS impact_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT impact_types_pkey PRIMARY KEY (id),
    CONSTRAINT impact_types_code_key UNIQUE (code),
    CONSTRAINT impact_types_name_key UNIQUE (name),
    CONSTRAINT impact_types_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT impact_types_name_not_empty CHECK (btrim(name) <> '')
);

CREATE TABLE IF NOT EXISTS analysis_output_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT analysis_output_types_pkey PRIMARY KEY (id),
    CONSTRAINT analysis_output_types_code_key UNIQUE (code),
    CONSTRAINT analysis_output_types_name_key UNIQUE (name),
    CONSTRAINT analysis_output_types_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT analysis_output_types_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE analysis_output_types IS
    'نوع ردیف عملیاتی که از تحلیل ساخته شده: وظیفه یا تصمیم.';

-- =============================================================================
-- حوزه سلسله‌مراتبی
-- =============================================================================

CREATE TABLE IF NOT EXISTS topics (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_id integer,
    code character varying(80) NOT NULL,
    name character varying(100) NOT NULL,
    level integer NOT NULL DEFAULT 1,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT topics_pkey PRIMARY KEY (id),
    CONSTRAINT topics_parent_id_fkey
        FOREIGN KEY (parent_id) REFERENCES topics(id) ON DELETE CASCADE,
    CONSTRAINT topics_code_key UNIQUE (code),
    CONSTRAINT topics_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT topics_name_not_empty CHECK (btrim(name) <> ''),
    CONSTRAINT topics_level_check CHECK (level >= 1)
);

COMMENT ON TABLE topics IS
    'درخت حوزه و زیرموضوع (مالی → پرداخت → تأخیر پرداخت). parent_id فقط برای ریشه خالی است.';

COMMENT ON COLUMN topics.parent_id IS
    'خالی یعنی حوزه سطح اول؛ برای زیرموضوع باید پر باشد.';

CREATE INDEX IF NOT EXISTS topics_parent_id_idx ON topics (parent_id);

-- =============================================================================
-- یک اجرای تحلیل روی یک منبع خام
-- =============================================================================

CREATE TABLE IF NOT EXISTS text_analyses (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    source_type_id integer NOT NULL,
    source_id integer NOT NULL,
    model character varying(120) NOT NULL,
    created_by_user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT text_analyses_pkey PRIMARY KEY (id),
    CONSTRAINT text_analyses_source_type_id_fkey
        FOREIGN KEY (source_type_id) REFERENCES analysis_source_types(id) ON DELETE RESTRICT,
    CONSTRAINT text_analyses_created_by_user_id_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT text_analyses_source_id_check CHECK (source_id > 0),
    CONSTRAINT text_analyses_model_not_empty CHECK (btrim(model) <> '')
);

COMMENT ON TABLE text_analyses IS
    'یک بار اجرای NLP روی متن خام ذخیره‌شده. منبع با source_type + source_id مشخص می‌شود؛ متن در جدول عملیاتی می‌ماند.';

CREATE INDEX IF NOT EXISTS text_analyses_source_idx
    ON text_analyses (source_type_id, source_id, created_at DESC);
CREATE INDEX IF NOT EXISTS text_analyses_created_by_idx
    ON text_analyses (created_by_user_id, created_at DESC);

-- طبقه‌بندی: فقط وقتی NLP آن برچسب را داده ردیف ساخته می‌شود.

CREATE TABLE IF NOT EXISTS text_analysis_discourses (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    discourse_type_id integer NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    CONSTRAINT text_analysis_discourses_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_discourses_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_discourses_discourse_type_id_fkey
        FOREIGN KEY (discourse_type_id) REFERENCES discourse_types(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_discourses_analysis_type_key
        UNIQUE (analysis_id, discourse_type_id),
    CONSTRAINT text_analysis_discourses_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS text_analysis_discourses_primary_idx
    ON text_analysis_discourses (analysis_id)
    WHERE is_primary;

CREATE TABLE IF NOT EXISTS text_analysis_intents (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    intent_id integer NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    CONSTRAINT text_analysis_intents_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_intents_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_intents_intent_id_fkey
        FOREIGN KEY (intent_id) REFERENCES intents(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_intents_analysis_intent_key
        UNIQUE (analysis_id, intent_id),
    CONSTRAINT text_analysis_intents_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS text_analysis_intents_primary_idx
    ON text_analysis_intents (analysis_id)
    WHERE is_primary;

CREATE TABLE IF NOT EXISTS text_analysis_topics (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    topic_id integer NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    CONSTRAINT text_analysis_topics_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_topics_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_topics_topic_id_fkey
        FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_topics_analysis_topic_key
        UNIQUE (analysis_id, topic_id),
    CONSTRAINT text_analysis_topics_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS text_analysis_topics_primary_idx
    ON text_analysis_topics (analysis_id)
    WHERE is_primary;

CREATE TABLE IF NOT EXISTS text_analysis_sentiments (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    polarity_id integer NOT NULL,
    intensity_id integer NOT NULL,
    CONSTRAINT text_analysis_sentiments_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_sentiments_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_sentiments_polarity_id_fkey
        FOREIGN KEY (polarity_id) REFERENCES polarities(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_sentiments_intensity_id_fkey
        FOREIGN KEY (intensity_id) REFERENCES intensity_levels(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_sentiments_analysis_id_key UNIQUE (analysis_id)
);

CREATE TABLE IF NOT EXISTS text_analysis_emotions (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    emotion_id integer NOT NULL,
    intensity_id integer NOT NULL,
    CONSTRAINT text_analysis_emotions_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_emotions_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_emotions_emotion_id_fkey
        FOREIGN KEY (emotion_id) REFERENCES emotions(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_emotions_intensity_id_fkey
        FOREIGN KEY (intensity_id) REFERENCES intensity_levels(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_emotions_analysis_emotion_key
        UNIQUE (analysis_id, emotion_id)
);

CREATE TABLE IF NOT EXISTS text_analysis_importances (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    importance_id integer NOT NULL,
    CONSTRAINT text_analysis_importances_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_importances_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_importances_importance_id_fkey
        FOREIGN KEY (importance_id) REFERENCES task_importances(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_importances_analysis_id_key UNIQUE (analysis_id)
);

CREATE TABLE IF NOT EXISTS text_analysis_urgencies (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    priority_id integer NOT NULL,
    CONSTRAINT text_analysis_urgencies_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_urgencies_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_urgencies_priority_id_fkey
        FOREIGN KEY (priority_id) REFERENCES task_priorities(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_urgencies_analysis_id_key UNIQUE (analysis_id)
);

-- خروجی عملیاتی ساخته‌شده از همین تحلیل (تسک / تصمیم موجود)

CREATE TABLE IF NOT EXISTS analysis_outputs (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    output_type_id integer NOT NULL,
    record_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT analysis_outputs_pkey PRIMARY KEY (id),
    CONSTRAINT analysis_outputs_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT analysis_outputs_output_type_id_fkey
        FOREIGN KEY (output_type_id) REFERENCES analysis_output_types(id) ON DELETE RESTRICT,
    CONSTRAINT analysis_outputs_analysis_type_record_key
        UNIQUE (analysis_id, output_type_id, record_id),
    CONSTRAINT analysis_outputs_record_id_check CHECK (record_id > 0)
);

COMMENT ON TABLE analysis_outputs IS
    'اتصال تحلیل به ردیف عملیاتی که CRUD بعد از استخراج ساخته (مثلاً tasks.id).';

-- =============================================================================
-- موجودیت canonical و ذکر در متن
-- =============================================================================

CREATE TABLE IF NOT EXISTS entities (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_type_id integer NOT NULL,
    status_id integer NOT NULL,
    canonical_name character varying(200) NOT NULL,
    normalized_name character varying(200) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT entities_pkey PRIMARY KEY (id),
    CONSTRAINT entities_entity_type_id_fkey
        FOREIGN KEY (entity_type_id) REFERENCES entity_types(id) ON DELETE RESTRICT,
    CONSTRAINT entities_status_id_fkey
        FOREIGN KEY (status_id) REFERENCES entity_statuses(id) ON DELETE RESTRICT,
    CONSTRAINT entities_canonical_name_not_empty CHECK (btrim(canonical_name) <> ''),
    CONSTRAINT entities_normalized_name_not_empty CHECK (btrim(normalized_name) <> '')
);

COMMENT ON TABLE entities IS
    'موجودیت canonical. وصل‌شدن به users/projects/tasks در جدول لینک جداست تا اینجا NULL نماند.';

CREATE INDEX IF NOT EXISTS entities_type_normalized_idx
    ON entities (entity_type_id, normalized_name);

CREATE TABLE IF NOT EXISTS entity_aliases (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_id integer NOT NULL,
    alias character varying(200) NOT NULL,
    CONSTRAINT entity_aliases_pkey PRIMARY KEY (id),
    CONSTRAINT entity_aliases_entity_id_fkey
        FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE,
    CONSTRAINT entity_aliases_entity_alias_key UNIQUE (entity_id, alias),
    CONSTRAINT entity_aliases_alias_not_empty CHECK (btrim(alias) <> '')
);

CREATE TABLE IF NOT EXISTS entity_mentions (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    entity_id integer NOT NULL,
    mention_text character varying(300) NOT NULL,
    start_offset integer NOT NULL,
    end_offset integer NOT NULL,
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    CONSTRAINT entity_mentions_pkey PRIMARY KEY (id),
    CONSTRAINT entity_mentions_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT entity_mentions_entity_id_fkey
        FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE RESTRICT,
    CONSTRAINT entity_mentions_span_key
        UNIQUE (analysis_id, entity_id, start_offset, end_offset),
    CONSTRAINT entity_mentions_mention_not_empty CHECK (btrim(mention_text) <> ''),
    CONSTRAINT entity_mentions_offsets_check
        CHECK (start_offset >= 0 AND end_offset > start_offset),
    CONSTRAINT entity_mentions_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

COMMENT ON TABLE entity_mentions IS
    'ذکر یک موجودیت در یک اجرای تحلیل. entity اول ساخته می‌شود بعد mention؛ بنابراین entity_id همیشه پر است.';

CREATE INDEX IF NOT EXISTS entity_mentions_entity_id_idx ON entity_mentions (entity_id);

CREATE TABLE IF NOT EXISTS entity_mention_times (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mention_id integer NOT NULL,
    occurred_at timestamp without time zone NOT NULL,
    CONSTRAINT entity_mention_times_pkey PRIMARY KEY (id),
    CONSTRAINT entity_mention_times_mention_id_fkey
        FOREIGN KEY (mention_id) REFERENCES entity_mentions(id) ON DELETE CASCADE,
    CONSTRAINT entity_mention_times_mention_id_key UNIQUE (mention_id)
);

COMMENT ON TABLE entity_mention_times IS
    'فقط برای ذکر نوع TIME که به تاریخ/ساعت مشخص تبدیل شده.';

CREATE TABLE IF NOT EXISTS entity_user_links (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT entity_user_links_pkey PRIMARY KEY (id),
    CONSTRAINT entity_user_links_entity_id_fkey
        FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE,
    CONSTRAINT entity_user_links_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT entity_user_links_entity_id_key UNIQUE (entity_id),
    CONSTRAINT entity_user_links_entity_user_key UNIQUE (entity_id, user_id)
);

CREATE TABLE IF NOT EXISTS entity_project_links (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_id integer NOT NULL,
    project_id integer NOT NULL,
    CONSTRAINT entity_project_links_pkey PRIMARY KEY (id),
    CONSTRAINT entity_project_links_entity_id_fkey
        FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE,
    CONSTRAINT entity_project_links_project_id_fkey
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT,
    CONSTRAINT entity_project_links_entity_id_key UNIQUE (entity_id)
);

CREATE TABLE IF NOT EXISTS entity_task_links (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_id integer NOT NULL,
    task_id integer NOT NULL,
    CONSTRAINT entity_task_links_pkey PRIMARY KEY (id),
    CONSTRAINT entity_task_links_entity_id_fkey
        FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE,
    CONSTRAINT entity_task_links_task_id_fkey
        FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE RESTRICT,
    CONSTRAINT entity_task_links_entity_id_key UNIQUE (entity_id)
);

CREATE TABLE IF NOT EXISTS entity_contact_links (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    entity_id integer NOT NULL,
    external_contact_id integer NOT NULL,
    CONSTRAINT entity_contact_links_pkey PRIMARY KEY (id),
    CONSTRAINT entity_contact_links_entity_id_fkey
        FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE,
    CONSTRAINT entity_contact_links_external_contact_id_fkey
        FOREIGN KEY (external_contact_id) REFERENCES external_contacts(id) ON DELETE RESTRICT,
    CONSTRAINT entity_contact_links_entity_id_key UNIQUE (entity_id)
);

CREATE TABLE IF NOT EXISTS entity_relations (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    relation_type_id integer NOT NULL,
    from_entity_id integer NOT NULL,
    to_entity_id integer NOT NULL,
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    CONSTRAINT entity_relations_pkey PRIMARY KEY (id),
    CONSTRAINT entity_relations_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT entity_relations_relation_type_id_fkey
        FOREIGN KEY (relation_type_id) REFERENCES relation_types(id) ON DELETE RESTRICT,
    CONSTRAINT entity_relations_from_entity_id_fkey
        FOREIGN KEY (from_entity_id) REFERENCES entities(id) ON DELETE RESTRICT,
    CONSTRAINT entity_relations_to_entity_id_fkey
        FOREIGN KEY (to_entity_id) REFERENCES entities(id) ON DELETE RESTRICT,
    CONSTRAINT entity_relations_pair_key
        UNIQUE (analysis_id, relation_type_id, from_entity_id, to_entity_id),
    CONSTRAINT entity_relations_not_self CHECK (from_entity_id <> to_entity_id),
    CONSTRAINT entity_relations_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

COMMENT ON TABLE entity_relations IS
    'رابطه استخراج‌شده بین دو موجودیت در همان اجرای تحلیل.';

CREATE INDEX IF NOT EXISTS entity_relations_from_idx ON entity_relations (from_entity_id);
CREATE INDEX IF NOT EXISTS entity_relations_to_idx ON entity_relations (to_entity_id);

-- =============================================================================
-- مسئله canonical (بین چند سند)
-- =============================================================================

CREATE TABLE IF NOT EXISTS issues (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    project_id integer NOT NULL,
    status_id integer NOT NULL,
    title character varying(200) NOT NULL,
    created_by_user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT issues_pkey PRIMARY KEY (id),
    CONSTRAINT issues_project_id_fkey
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT,
    CONSTRAINT issues_status_id_fkey
        FOREIGN KEY (status_id) REFERENCES issue_statuses(id) ON DELETE RESTRICT,
    CONSTRAINT issues_created_by_user_id_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT issues_title_not_empty CHECK (btrim(title) <> '')
);

COMMENT ON TABLE issues IS
    'مسئله واحد پروژه که چند گزارش/پیام/جلسه می‌توانند به آن وصل شوند.';

CREATE INDEX IF NOT EXISTS issues_project_status_idx ON issues (project_id, status_id);

CREATE TABLE IF NOT EXISTS issue_sources (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    issue_id integer NOT NULL,
    analysis_id integer NOT NULL,
    CONSTRAINT issue_sources_pkey PRIMARY KEY (id),
    CONSTRAINT issue_sources_issue_id_fkey
        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT issue_sources_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT issue_sources_issue_analysis_key UNIQUE (issue_id, analysis_id)
);

COMMENT ON TABLE issue_sources IS
    'کدام اجرای تحلیل این مسئله را از متن درآورده یا به آن وصل کرده.';

CREATE TABLE IF NOT EXISTS issue_topics (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    issue_id integer NOT NULL,
    topic_id integer NOT NULL,
    CONSTRAINT issue_topics_pkey PRIMARY KEY (id),
    CONSTRAINT issue_topics_issue_id_fkey
        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT issue_topics_topic_id_fkey
        FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE RESTRICT,
    CONSTRAINT issue_topics_issue_topic_key UNIQUE (issue_id, topic_id)
);

CREATE TABLE IF NOT EXISTS issue_entities (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    issue_id integer NOT NULL,
    entity_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT issue_entities_pkey PRIMARY KEY (id),
    CONSTRAINT issue_entities_issue_id_fkey
        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT issue_entities_entity_id_fkey
        FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE RESTRICT,
    CONSTRAINT issue_entities_role_id_fkey
        FOREIGN KEY (role_id) REFERENCES issue_entity_roles(id) ON DELETE RESTRICT,
    CONSTRAINT issue_entities_issue_entity_role_key UNIQUE (issue_id, entity_id, role_id)
);

CREATE TABLE IF NOT EXISTS issue_causes (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    issue_id integer NOT NULL,
    cause_issue_id integer NOT NULL,
    cause_level_id integer NOT NULL,
    CONSTRAINT issue_causes_pkey PRIMARY KEY (id),
    CONSTRAINT issue_causes_issue_id_fkey
        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT issue_causes_cause_issue_id_fkey
        FOREIGN KEY (cause_issue_id) REFERENCES issues(id) ON DELETE RESTRICT,
    CONSTRAINT issue_causes_cause_level_id_fkey
        FOREIGN KEY (cause_level_id) REFERENCES cause_levels(id) ON DELETE RESTRICT,
    CONSTRAINT issue_causes_pair_key UNIQUE (issue_id, cause_issue_id),
    CONSTRAINT issue_causes_not_self CHECK (issue_id <> cause_issue_id)
);

COMMENT ON TABLE issue_causes IS
    'زنجیره مسئله ← علت ← ریشه؛ هر حلقه یک ردیف است.';

CREATE TABLE IF NOT EXISTS issue_importances (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    issue_id integer NOT NULL,
    importance_id integer NOT NULL,
    CONSTRAINT issue_importances_pkey PRIMARY KEY (id),
    CONSTRAINT issue_importances_issue_id_fkey
        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT issue_importances_importance_id_fkey
        FOREIGN KEY (importance_id) REFERENCES task_importances(id) ON DELETE RESTRICT,
    CONSTRAINT issue_importances_issue_id_key UNIQUE (issue_id)
);

CREATE TABLE IF NOT EXISTS issue_urgencies (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    issue_id integer NOT NULL,
    priority_id integer NOT NULL,
    CONSTRAINT issue_urgencies_pkey PRIMARY KEY (id),
    CONSTRAINT issue_urgencies_issue_id_fkey
        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT issue_urgencies_priority_id_fkey
        FOREIGN KEY (priority_id) REFERENCES task_priorities(id) ON DELETE RESTRICT,
    CONSTRAINT issue_urgencies_issue_id_key UNIQUE (issue_id)
);

CREATE TABLE IF NOT EXISTS issue_severities (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    issue_id integer NOT NULL,
    severity_id integer NOT NULL,
    CONSTRAINT issue_severities_pkey PRIMARY KEY (id),
    CONSTRAINT issue_severities_issue_id_fkey
        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT issue_severities_severity_id_fkey
        FOREIGN KEY (severity_id) REFERENCES severity_levels(id) ON DELETE RESTRICT,
    CONSTRAINT issue_severities_issue_id_key UNIQUE (issue_id)
);

CREATE TABLE IF NOT EXISTS issue_impacts (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    issue_id integer NOT NULL,
    impact_type_id integer NOT NULL,
    description character varying(300) NOT NULL,
    CONSTRAINT issue_impacts_pkey PRIMARY KEY (id),
    CONSTRAINT issue_impacts_issue_id_fkey
        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT issue_impacts_impact_type_id_fkey
        FOREIGN KEY (impact_type_id) REFERENCES impact_types(id) ON DELETE RESTRICT,
    CONSTRAINT issue_impacts_description_not_empty CHECK (btrim(description) <> '')
);

CREATE TABLE IF NOT EXISTS issue_tasks (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    issue_id integer NOT NULL,
    task_id integer NOT NULL,
    CONSTRAINT issue_tasks_pkey PRIMARY KEY (id),
    CONSTRAINT issue_tasks_issue_id_fkey
        FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE,
    CONSTRAINT issue_tasks_task_id_fkey
        FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT issue_tasks_issue_task_key UNIQUE (issue_id, task_id)
);

COMMENT ON TABLE issue_tasks IS
    'اقدام استخراج‌شده بعد از تأیید در tasks ثبت می‌شود و اینجا به مسئله وصل می‌گردد.';

-- =============================================================================
-- Seed lookup
-- =============================================================================

INSERT INTO analysis_source_types (code, name, description, is_active) VALUES
    ('report', 'گزارش', 'جدول reports', true),
    ('meeting', 'جلسه', 'جدول meetings', true),
    ('message', 'پیام', 'جدول messages', true),
    ('idea_experience', 'ایده و تجربه', 'جدول ideas_experiences', true),
    ('task', 'وظیفه', 'جدول tasks', true),
    ('task_follow_up', 'پیگیری وظیفه', 'جدول task_follow_ups', true),
    ('project_document', 'مستند پروژه', 'جدول project_documents', true),
    ('content', 'محتوا', 'جدول contents؛ پیش‌نویس متن آزاد playground', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO discourse_types (code, name, description, is_active) VALUES
    ('order', 'دستور', 'الزام از موضع اختیار؛ آمر و مأمور و تکلیف لازم است', true),
    ('resolution', 'مصوبه', 'تصمیم استنادپذیر با مرجع تصویب رسمی', true),
    ('decision', 'تصمیم', 'انتخاب قطعی گرفته‌شده؛ هنوز توصیه نیست', true),
    ('request', 'درخواست', 'طلب انجام کار بدون اعمال قدرت', true),
    ('question', 'سؤال', 'طلب دانستن؛ مطلوب عمل نیست', true),
    ('warning', 'هشدار', 'ریسک نزدیک؛ اختلال رخ‌داده مسئله است', true),
    ('solution', 'راهکار', 'روش حل مسئلهٔ حاضر', true),
    ('suggestion', 'پیشنهاد', 'توصیهٔ اجرایی خطاب به تصمیم‌گیر', true),
    ('idea', 'ایده', 'طرح نو بدون خطاب اجرایی', true),
    ('issue', 'مسئله', 'مانع یا اختلال نیازمند رسیدگی؛ شامل مشکل', true),
    ('result', 'نتیجه', 'حاصل تمام‌شدهٔ کار یا آزمون', true),
    ('analysis', 'تحلیل', 'بررسی با شاهد و استنتاج', true),
    ('interpretation', 'توضیح و تفسیر', 'روشن کردن معنا نه راه‌حل', true),
    ('feedback', 'بازخورد', 'ارزیابی کار یا خروجی مشخص', true),
    ('experience', 'تجربه', 'روایت گذشته با پیامد و درس', true),
    ('announcement', 'اطلاعیه', 'ابلاغ یک‌طرفه خبر به جمع', true),
    ('report', 'گزارش', 'روایت وضعیت یا وقایع؛ رخداد جدا نیست', true),
    ('note', 'یادداشت', 'ثبت کوتاه بدون انتظار واکنش فوری', true),
    ('answer', 'پاسخ', 'پر کردن مجهول قبلی', true),
    ('message', 'پیام', 'فقط وقتی هیچ ژانر دیگری پر نشود', true),
    ('problem', 'مشکل', 'ادغام‌شده در مسئله؛ برای استخراج فعال نیست', false),
    ('action', 'اقدام', 'ادغام‌شده در گزارش یا نتیجه؛ برای استخراج فعال نیست', false),
    ('event', 'رخداد', 'ادغام‌شده در گزارش؛ برای استخراج فعال نیست', false)
ON CONFLICT (code) DO NOTHING;

INSERT INTO intents (code, name, description, is_active) VALUES
    ('complaint', 'شکایت', 'شاکی، مشتکی‌عنه، مورد اختلاف و خواسته لازم است', true),
    ('objection', 'اعتراض', 'مخالفت با حکم یا برداشت بدون لزوماً جبران', true),
    ('reject', 'رد', 'نپذیرفتن پیشنهاد یا تحویل روی میز', true),
    ('approve', 'تأیید', 'پذیرفتن پیشنهاد یا تحویل روی میز', true),
    ('request_decision', 'درخواست تصمیم', 'مخاطب باید انتخاب کند نه لزوماً اجرا', true),
    ('request_action', 'درخواست اقدام', 'مخاطب باید کاری انجام دهد', true),
    ('follow_up', 'پیگیری', 'مورد باز قبلی معطل مانده', true),
    ('request_info', 'درخواست اطلاعات', 'مخاطب باید چیزی بگوید یا بفرستد', true),
    ('report_problem', 'گزارش مشکل', 'مسئله بدون مقصرسازی و طلب جبران', true),
    ('inform', 'اطلاع‌رسانی', 'فقط دانستن؛ غرض دیگری نیست', true),
    ('suggest', 'پیشنهاد', 'تکرار ژانر؛ برای استخراج نیت فعال نیست', false),
    ('question', 'سؤال', 'تکرار ژانر؛ برای استخراج نیت فعال نیست', false),
    ('answer', 'پاسخ', 'تکرار ژانر؛ برای استخراج نیت فعال نیست', false),
    ('warn', 'هشدار', 'تکرار ژانر؛ برای استخراج نیت فعال نیست', false)
ON CONFLICT (code) DO NOTHING;

INSERT INTO entity_types (code, name, is_active) VALUES
    ('PERSON', 'فرد', true),
    ('UNIT', 'واحد', true),
    ('ORG', 'سازمان', true),
    ('PLACE', 'مکان', true),
    ('OBJECT', 'شیء', true),
    ('PROJECT', 'پروژه', true),
    ('TASK', 'وظیفه', true),
    ('TIME', 'زمان', true),
    ('ROLE', 'نقش', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO entity_statuses (code, name, is_active) VALUES
    ('candidate', 'پیشنهادی', true),
    ('confirmed', 'تأییدشده', true),
    ('rejected', 'ردشده', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO relation_types (code, name, is_active) VALUES
    ('causes', 'علت', true),
    ('responsible_for', 'مسئولیت', true),
    ('impacts', 'پیامد', true),
    ('depends_on', 'وابستگی', true),
    ('contradicts', 'تناقض', true),
    ('related_to', 'مرتبط', true),
    ('assigned_to', 'واگذاری', true),
    ('occurred_at', 'زمان وقوع', true),
    ('part_of', 'جزء', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO polarities (code, name, is_active) VALUES
    ('positive', 'مثبت', true),
    ('negative', 'منفی', true),
    ('neutral', 'خنثی', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO emotions (code, name, is_active) VALUES
    ('frustration', 'خستگی و نارضایتی', true),
    ('anger', 'خشم', true),
    ('worry', 'نگرانی', true),
    ('satisfaction', 'رضایت', true),
    ('confidence', 'اطمینان', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO intensity_levels (code, name, level, is_active) VALUES
    ('low', 'کم', 1, true),
    ('medium', 'متوسط', 2, true),
    ('high', 'زیاد', 3, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO severity_levels (code, name, level, is_active) VALUES
    ('low', 'کم', 1, true),
    ('medium', 'متوسط', 2, true),
    ('high', 'زیاد', 3, true),
    ('critical', 'بحرانی', 4, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO issue_statuses (code, name, is_active) VALUES
    ('new', 'جدید', true),
    ('open', 'باز', true),
    ('reviewing', 'در حال بررسی', true),
    ('waiting', 'در انتظار', true),
    ('referred', 'ارجاع شده', true),
    ('in_progress', 'در حال انجام', true),
    ('done', 'انجام شده', true),
    ('resolved', 'حل شده', true),
    ('closed', 'بسته شده', true),
    ('cancelled', 'لغو شده', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO cause_levels (code, name, level, is_active) VALUES
    ('cause', 'علت', 1, true),
    ('root_cause', 'ریشه', 2, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO issue_entity_roles (code, name, is_active) VALUES
    ('responsible', 'مسئول', true),
    ('affected', 'متأثر', true),
    ('mentioned', 'ذکرشده', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO impact_types (code, name, is_active) VALUES
    ('time', 'زمان', true),
    ('cost', 'هزینه', true),
    ('budget', 'بودجه', true),
    ('quality', 'کیفیت', true),
    ('sales', 'فروش', true),
    ('customer', 'مشتری', true),
    ('revenue', 'درآمد', true),
    ('hr', 'منابع انسانی', true),
    ('goal', 'اهداف پروژه', true),
    ('risk', 'ریسک', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO analysis_output_types (code, name, is_active) VALUES
    ('task', 'وظیفه', true),
    ('idea_experience', 'تصمیم / ایده', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO topics (code, name, level, is_active) VALUES
    ('finance', 'مالی', 1, true),
    ('tech', 'فنی', 1, true),
    ('sales', 'فروش', 1, true),
    ('marketing', 'بازاریابی', 1, true),
    ('procurement', 'تدارکات', 1, true),
    ('hr', 'منابع انسانی', 1, true),
    ('legal', 'حقوقی', 1, true),
    ('management', 'هماهنگی و مدیریت', 1, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO topics (parent_id, code, name, level, is_active)
SELECT id, 'finance.payment', 'پرداخت', 2, true
FROM topics WHERE code = 'finance'
ON CONFLICT (code) DO NOTHING;

INSERT INTO topics (parent_id, code, name, level, is_active)
SELECT id, 'finance.payment.delay', 'تأخیر پرداخت', 3, true
FROM topics WHERE code = 'finance.payment'
ON CONFLICT (code) DO NOTHING;

INSERT INTO topics (parent_id, code, name, level, is_active)
SELECT id, 'tech.software', 'نرم‌افزار', 2, true
FROM topics WHERE code = 'tech'
ON CONFLICT (code) DO NOTHING;

INSERT INTO topics (parent_id, code, name, level, is_active)
SELECT id, 'tech.hardware', 'سخت‌افزار', 2, true
FROM topics WHERE code = 'tech'
ON CONFLICT (code) DO NOTHING;

INSERT INTO topics (parent_id, code, name, level, is_active)
SELECT id, 'tech.test', 'تست', 2, true
FROM topics WHERE code = 'tech'
ON CONFLICT (code) DO NOTHING;

INSERT INTO topics (parent_id, code, name, level, is_active)
SELECT id, 'tech.software.auth', 'احراز هویت', 3, true
FROM topics WHERE code = 'tech.software'
ON CONFLICT (code) DO NOTHING;

COMMIT;
