-- اجزای نیت و بردار بازیابی معنایی.
-- متن خام و فکت استخراج‌شده جدا ذخیره می‌شوند؛ منبع حقیقت جداول تحلیل است.

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE text_analysis_topics
    ADD COLUMN IF NOT EXISTS mention_text character varying(300) NOT NULL DEFAULT '';

ALTER TABLE text_analysis_sentiments
    ADD COLUMN IF NOT EXISTS mention_text character varying(300) NOT NULL DEFAULT '';

ALTER TABLE text_analysis_emotions
    ADD COLUMN IF NOT EXISTS mention_text character varying(300) NOT NULL DEFAULT '';

ALTER TABLE text_analysis_discourses
    ADD COLUMN IF NOT EXISTS mention_text character varying(300) NOT NULL DEFAULT '';

ALTER TABLE text_analysis_intents
    ADD COLUMN IF NOT EXISTS mention_text character varying(300) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS text_analysis_intent_slots (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_intent_id integer NOT NULL,
    slot_name character varying(100) NOT NULL,
    slot_value character varying(300) NOT NULL,
    CONSTRAINT text_analysis_intent_slots_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_intent_slots_analysis_intent_id_fkey
        FOREIGN KEY (analysis_intent_id) REFERENCES text_analysis_intents(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_intent_slots_unique
        UNIQUE (analysis_intent_id, slot_name),
    CONSTRAINT text_analysis_intent_slots_name_not_empty CHECK (btrim(slot_name) <> ''),
    CONSTRAINT text_analysis_intent_slots_value_not_empty CHECK (btrim(slot_value) <> '')
);

COMMENT ON TABLE text_analysis_intent_slots IS
    'نقش‌های پرشدهٔ یک نیت استخراج‌شده؛ شاکی، خواسته، و بقیهٔ اجزای کاتالوگ.';

CREATE INDEX IF NOT EXISTS text_analysis_intent_slots_intent_idx
    ON text_analysis_intent_slots (analysis_intent_id);

CREATE TABLE IF NOT EXISTS text_embeddings (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    kind character varying(40) NOT NULL,
    record_id integer,
    chunk_index integer NOT NULL DEFAULT 0,
    embedded_text text NOT NULL,
    model character varying(120) NOT NULL,
    embedding vector(1536) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT text_embeddings_pkey PRIMARY KEY (id),
    CONSTRAINT text_embeddings_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_embeddings_kind_check
        CHECK (kind IN ('raw', 'entity', 'intent', 'intent_slot')),
    CONSTRAINT text_embeddings_chunk_index_check CHECK (chunk_index >= 0),
    CONSTRAINT text_embeddings_embedded_text_not_empty CHECK (btrim(embedded_text) <> ''),
    CONSTRAINT text_embeddings_model_not_empty CHECK (btrim(model) <> '')
);

COMMENT ON TABLE text_embeddings IS
    'بردار بازیابی با pgvector. منبع حقیقت نیست؛ raw متن خام است و بقیه فکت استخراج‌شده.';

CREATE UNIQUE INDEX IF NOT EXISTS text_embeddings_unique_idx
    ON text_embeddings (analysis_id, kind, COALESCE(record_id, 0), chunk_index);

CREATE INDEX IF NOT EXISTS text_embeddings_analysis_kind_idx
    ON text_embeddings (analysis_id, kind);

CREATE INDEX IF NOT EXISTS text_embeddings_model_idx
    ON text_embeddings (model);

COMMIT;
