-- ژانر کشف‌شده از متن و نقش‌های پرشدهٔ همان ژانر.
-- نوع نو ردیف discourse_types می‌گیرد؛ ساختارش حذف یا به قالب قبلی تقلیل نمی‌شود.

BEGIN;

ALTER TABLE discourse_types
    ADD COLUMN IF NOT EXISTS is_discovered boolean NOT NULL DEFAULT false;

COMMENT ON TABLE discourse_types IS
    'ژانر متن استخراج‌شده (گزارش، درخواست، ...). ردیف کشف‌شده از متن با is_discovered مشخص می‌شود.';

CREATE TABLE IF NOT EXISTS text_analysis_discourse_slots (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_discourse_id integer NOT NULL,
    slot_name character varying(100) NOT NULL,
    slot_value character varying(300) NOT NULL,
    CONSTRAINT text_analysis_discourse_slots_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_discourse_slots_analysis_discourse_id_fkey
        FOREIGN KEY (analysis_discourse_id) REFERENCES text_analysis_discourses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_discourse_slots_unique
        UNIQUE (analysis_discourse_id, slot_name),
    CONSTRAINT text_analysis_discourse_slots_name_not_empty CHECK (btrim(slot_name) <> ''),
    CONSTRAINT text_analysis_discourse_slots_value_not_empty CHECK (btrim(slot_value) <> '')
);

COMMENT ON TABLE text_analysis_discourse_slots IS
    'نقش‌های پرشدهٔ یک ژانر استخراج‌شده؛ برای نوع کشف‌شده ساختار همان نوع است.';

CREATE INDEX IF NOT EXISTS text_analysis_discourse_slots_discourse_idx
    ON text_analysis_discourse_slots (analysis_discourse_id);

COMMIT;
