-- صنعت بیان متن: کنایه، طعنه، طنز، استعاره و صریح.
-- نیت و ژانر نیست؛ اعتراض کنایه‌ای همچنان اعتراض می‌ماند.

BEGIN;

CREATE TABLE IF NOT EXISTS rhetoric_types (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT rhetoric_types_pkey PRIMARY KEY (id),
    CONSTRAINT rhetoric_types_code_key UNIQUE (code),
    CONSTRAINT rhetoric_types_name_key UNIQUE (name),
    CONSTRAINT rhetoric_types_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT rhetoric_types_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE rhetoric_types IS
    'صنعت بیان متن (صریح، کنایه، طعنه، طنز، استعاره، ...). با نیت و ژانر فرق دارد.';

CREATE TABLE IF NOT EXISTS text_analysis_rhetorics (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    rhetoric_type_id integer NOT NULL,
    is_primary boolean NOT NULL DEFAULT false,
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    mention_text character varying(300) NOT NULL DEFAULT '',
    intended_meaning text NOT NULL DEFAULT '',
    CONSTRAINT text_analysis_rhetorics_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_rhetorics_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_rhetorics_rhetoric_type_id_fkey
        FOREIGN KEY (rhetoric_type_id) REFERENCES rhetoric_types(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_rhetorics_analysis_type_key
        UNIQUE (analysis_id, rhetoric_type_id),
    CONSTRAINT text_analysis_rhetorics_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

COMMENT ON TABLE text_analysis_rhetorics IS
    'صنعت بیان استخراج‌شده برای یک تحلیل. معنای مقصود بازنویسیٔ صریح غرض است.';

CREATE UNIQUE INDEX IF NOT EXISTS text_analysis_rhetorics_primary_idx
    ON text_analysis_rhetorics (analysis_id)
    WHERE is_primary;

CREATE TABLE IF NOT EXISTS text_analysis_rhetoric_slots (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_rhetoric_id integer NOT NULL,
    slot_name character varying(100) NOT NULL,
    slot_value character varying(300) NOT NULL,
    CONSTRAINT text_analysis_rhetoric_slots_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_rhetoric_slots_analysis_rhetoric_id_fkey
        FOREIGN KEY (analysis_rhetoric_id) REFERENCES text_analysis_rhetorics(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_rhetoric_slots_unique
        UNIQUE (analysis_rhetoric_id, slot_name),
    CONSTRAINT text_analysis_rhetoric_slots_name_not_empty CHECK (btrim(slot_name) <> ''),
    CONSTRAINT text_analysis_rhetoric_slots_value_not_empty CHECK (btrim(slot_value) <> '')
);

COMMENT ON TABLE text_analysis_rhetoric_slots IS
    'نقش‌های پرشدهٔ یک صنعت بیان؛ ظاهر، مقصود، هدف طعنه و مانند آن.';

CREATE INDEX IF NOT EXISTS text_analysis_rhetoric_slots_rhetoric_idx
    ON text_analysis_rhetoric_slots (analysis_rhetoric_id);

INSERT INTO rhetoric_types (code, name, description, is_active) VALUES
    ('sarcasm', 'طعنه', 'کنایهٔ نیش‌دار خطاب به فرد یا واحد', true),
    ('irony', 'کنایه', 'معنا خلاف ظاهر است', true),
    ('rhetorical_question', 'سؤال بلاغی', 'ظاهر سؤال، غرض اعتراض یا فشار است', true),
    ('humor', 'طنز', 'شوخی؛ ممکن است اعتراض را بپوشاند', true),
    ('metaphor', 'استعاره', 'چیزی به‌جای چیز دیگر بدون ادات تشبیه', true),
    ('simile', 'تشبیه', 'مانند یا مثل برای رساندن معنا', true),
    ('hyperbole', 'اغراق', 'بزرگ‌نمایی برای فشار', true),
    ('understatement', 'کم‌گویی', 'کوچک‌نمایی برای اعتراض', true),
    ('literal', 'صریح', 'فقط وقتی هیچ صنعت دیگری پر نشود', true)
ON CONFLICT (code) DO NOTHING;

COMMIT;
