-- فکت عددی و علت استخراج‌شده روی همان تحلیل متن.
-- نقل‌قول، رابطه موجودیت و امبدینگ فکت اینجا نیست.

BEGIN;

CREATE TABLE IF NOT EXISTS fact_kinds (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT fact_kinds_pkey PRIMARY KEY (id),
    CONSTRAINT fact_kinds_code_key UNIQUE (code),
    CONSTRAINT fact_kinds_name_key UNIQUE (name),
    CONSTRAINT fact_kinds_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT fact_kinds_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE fact_kinds IS
    'نوع فکت استخراج‌شده: مقدار، شرط، تغییر، علت، وضعیت.';

CREATE TABLE IF NOT EXISTS fact_units (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT fact_units_pkey PRIMARY KEY (id),
    CONSTRAINT fact_units_code_key UNIQUE (code),
    CONSTRAINT fact_units_name_key UNIQUE (name),
    CONSTRAINT fact_units_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT fact_units_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE fact_units IS
    'واحد مقدار فکت: درصد، مبلغ، تعداد، مدت، نسبت.';

CREATE TABLE IF NOT EXISTS fact_quantity_roles (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT fact_quantity_roles_pkey PRIMARY KEY (id),
    CONSTRAINT fact_quantity_roles_code_key UNIQUE (code),
    CONSTRAINT fact_quantity_roles_name_key UNIQUE (name),
    CONSTRAINT fact_quantity_roles_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT fact_quantity_roles_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE fact_quantity_roles IS
    'نقش مقدار: کل، جزء، باقی‌مانده، یا بدون نقش.';

CREATE TABLE IF NOT EXISTS fact_groundings (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT fact_groundings_pkey PRIMARY KEY (id),
    CONSTRAINT fact_groundings_code_key UNIQUE (code),
    CONSTRAINT fact_groundings_name_key UNIQUE (name),
    CONSTRAINT fact_groundings_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT fact_groundings_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE fact_groundings IS
    'صراحت فکت: صریح در متن یا مستنتج از شاهد.';

CREATE TABLE IF NOT EXISTS fact_derivations (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT fact_derivations_pkey PRIMARY KEY (id),
    CONSTRAINT fact_derivations_code_key UNIQUE (code),
    CONSTRAINT fact_derivations_name_key UNIQUE (name),
    CONSTRAINT fact_derivations_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT fact_derivations_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE fact_derivations IS
    'عمل استنتاج عددی: تفریق، جمع، باقی‌مانده، از شاهد متن.';

CREATE TABLE IF NOT EXISTS text_analysis_facts (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    fact_code character varying(40) NOT NULL DEFAULT '',
    kind_id integer NOT NULL,
    name character varying(200) NOT NULL,
    value numeric(12, 4),
    unit_id integer,
    role_id integer NOT NULL,
    grounding_id integer NOT NULL,
    derivation_id integer,
    effect character varying(300) NOT NULL DEFAULT '',
    previous character varying(300) NOT NULL DEFAULT '',
    current character varying(300) NOT NULL DEFAULT '',
    mention_text character varying(300) NOT NULL DEFAULT '',
    start_offset integer,
    end_offset integer,
    evidence_texts text[] NOT NULL DEFAULT '{}',
    source_ids text[] NOT NULL DEFAULT '{}',
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    CONSTRAINT text_analysis_facts_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_facts_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_facts_kind_id_fkey
        FOREIGN KEY (kind_id) REFERENCES fact_kinds(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_facts_unit_id_fkey
        FOREIGN KEY (unit_id) REFERENCES fact_units(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_facts_role_id_fkey
        FOREIGN KEY (role_id) REFERENCES fact_quantity_roles(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_facts_grounding_id_fkey
        FOREIGN KEY (grounding_id) REFERENCES fact_groundings(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_facts_derivation_id_fkey
        FOREIGN KEY (derivation_id) REFERENCES fact_derivations(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_facts_name_not_empty CHECK (btrim(name) <> ''),
    CONSTRAINT text_analysis_facts_offsets_check
        CHECK (
            (start_offset IS NULL AND end_offset IS NULL)
            OR (start_offset >= 0 AND end_offset > start_offset)
        ),
    CONSTRAINT text_analysis_facts_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

COMMENT ON TABLE text_analysis_facts IS
    'فکت استخراج‌شده برای یک تحلیل: مقدار، نقش total/part/remainder، صراحت و شاهد.';

CREATE INDEX IF NOT EXISTS text_analysis_facts_analysis_idx
    ON text_analysis_facts (analysis_id);

INSERT INTO fact_kinds (code, name, description, is_active) VALUES
    ('quantity', 'مقدار', 'عدد یا درصد که در متن آمده یا از عددهای صریح قابل محاسبه است', true),
    ('condition', 'شرط', 'قیدی که وقوع یا پذیرش به آن وابسته است', true),
    ('change', 'تغییر', 'فرق وضعیت فعلی با قبل؛ کاهش، افزایش، جایگزینی', true),
    ('cause', 'علت', 'نسبت علت و معلول که شاهدش در متن باشد', true),
    ('status', 'وضعیت', 'وضع فعلی کار یا واحد، بدون عدد الزامی', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO fact_units (code, name, description, is_active) VALUES
    ('percent', 'درصد', NULL, true),
    ('amount', 'مبلغ', NULL, true),
    ('count', 'تعداد', NULL, true),
    ('duration', 'مدت', NULL, true),
    ('ratio', 'نسبت', NULL, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO fact_quantity_roles (code, name, description, is_active) VALUES
    ('total', 'کل', NULL, true),
    ('part', 'جزء', NULL, true),
    ('remainder', 'باقی‌مانده', NULL, true),
    ('none', 'بدون نقش', NULL, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO fact_groundings (code, name, description, is_active) VALUES
    ('explicit', 'صریح', 'خودِ مقدار یا ادعا زیررشتهٔ متن است', true),
    ('derived', 'مستنتج از شاهد', 'مقدار در متن نیست ولی از فکت‌های صریح با عمل مجاز به‌دست می‌آید', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO fact_derivations (code, name, description, is_active) VALUES
    ('subtract', 'تفریق', 'مقدار = منبع اول منهای مجموع بقیه', true),
    ('add', 'جمع', 'مقدار = مجموع منابع', true),
    ('remainder', 'باقی‌مانده', 'مقدار = کل منهای اجزا', true),
    ('from_evidence', 'از شاهد متن', 'استنتاج غیرعددی؛ همهٔ evidence_texts باید در متن باشند', true)
ON CONFLICT (code) DO NOTHING;

COMMIT;
