-- نقل‌قول استخراج‌شده روی همان تحلیل متن.
-- رابطه موجودیت و امبدینگ نقل و ارسال یادآوری اینجا نیست.

BEGIN;

CREATE TABLE IF NOT EXISTS quote_modes (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT quote_modes_pkey PRIMARY KEY (id),
    CONSTRAINT quote_modes_code_key UNIQUE (code),
    CONSTRAINT quote_modes_name_key UNIQUE (name),
    CONSTRAINT quote_modes_code_not_empty CHECK (btrim(code) <> ''),
    CONSTRAINT quote_modes_name_not_empty CHECK (btrim(name) <> '')
);

COMMENT ON TABLE quote_modes IS
    'شیوه نقل: مستقیم یا غیرمستقیم.';

CREATE TABLE IF NOT EXISTS text_analysis_quotes (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    mode_id integer NOT NULL,
    attributed_to character varying(200) NOT NULL,
    quoted_text text NOT NULL,
    mention_text character varying(300) NOT NULL DEFAULT '',
    start_offset integer,
    end_offset integer,
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    CONSTRAINT text_analysis_quotes_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_quotes_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_quotes_mode_id_fkey
        FOREIGN KEY (mode_id) REFERENCES quote_modes(id) ON DELETE RESTRICT,
    CONSTRAINT text_analysis_quotes_speaker_not_empty
        CHECK (btrim(attributed_to) <> ''),
    CONSTRAINT text_analysis_quotes_text_not_empty
        CHECK (btrim(quoted_text) <> ''),
    CONSTRAINT text_analysis_quotes_offsets_check
        CHECK (
            (start_offset IS NULL AND end_offset IS NULL)
            OR (start_offset >= 0 AND end_offset > start_offset)
        ),
    CONSTRAINT text_analysis_quotes_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

COMMENT ON TABLE text_analysis_quotes IS
    'نقل‌قول استخراج‌شده برای یک تحلیل: گوینده، شیوه مستقیم/غیرمستقیم، متن نقل، شاهد و آفست.';

CREATE INDEX IF NOT EXISTS text_analysis_quotes_analysis_idx
    ON text_analysis_quotes (analysis_id);

INSERT INTO quote_modes (code, name, description, is_active) VALUES
    ('direct', 'مستقیم', 'نقل قول با علامت یا بازنویسی نزدیک «گفت که …»', true),
    ('indirect', 'غیرمستقیم', 'گزارش سخن دیگری بدون لزوماً گیومه؛ «رفتم واحد مالی گفت»', true)
ON CONFLICT (code) DO NOTHING;

COMMIT;
