-- کلمهٔ کلیدی آزاد استخراج‌شده روی همان تحلیل متن.
-- موجودیت نام‌دار این جدول نیست؛ آن‌ها در entity_mentions می‌مانند.

BEGIN;

CREATE TABLE IF NOT EXISTS text_analysis_keywords (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    analysis_id integer NOT NULL,
    phrase character varying(200) NOT NULL,
    mention_text character varying(300) NOT NULL DEFAULT '',
    start_offset integer,
    end_offset integer,
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    CONSTRAINT text_analysis_keywords_pkey PRIMARY KEY (id),
    CONSTRAINT text_analysis_keywords_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT text_analysis_keywords_phrase_not_empty
        CHECK (btrim(phrase) <> ''),
    CONSTRAINT text_analysis_keywords_offsets_check
        CHECK (
            (start_offset IS NULL AND end_offset IS NULL)
            OR (start_offset >= 0 AND end_offset > start_offset)
        ),
    CONSTRAINT text_analysis_keywords_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

COMMENT ON TABLE text_analysis_keywords IS
    'عبارت کلیدی آزاد یک تحلیل؛ موجودیت نام‌دار نیست.';

CREATE INDEX IF NOT EXISTS text_analysis_keywords_analysis_idx
    ON text_analysis_keywords (analysis_id);

COMMIT;
