-- کلمهٔ کلیدی جدول دامنه جدا است، نه فقط فرزند تحلیل.
-- ذکر به متن خام (source_type + source_id)، پروژه و صاحب متن وصل می‌شود.
-- project_id روی خود تحلیل هم می‌آید تا بقیهٔ لایه‌ها پروژه را از منبع بفهمند.

BEGIN;

ALTER TABLE text_analyses
    ADD COLUMN IF NOT EXISTS project_id integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'text_analyses_project_id_fkey'
    ) THEN
        ALTER TABLE text_analyses
            ADD CONSTRAINT text_analyses_project_id_fkey
            FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS text_analyses_project_idx
    ON text_analyses (project_id, created_at DESC)
    WHERE project_id IS NOT NULL;

UPDATE text_analyses a
SET project_id = r.project_id
FROM analysis_source_types st, reports r
WHERE st.id = a.source_type_id AND st.code = 'report' AND r.id = a.source_id
  AND a.project_id IS NULL;

UPDATE text_analyses a
SET project_id = mt.project_id
FROM analysis_source_types st, meetings mt
WHERE st.id = a.source_type_id AND st.code = 'meeting' AND mt.id = a.source_id
  AND a.project_id IS NULL;

UPDATE text_analyses a
SET project_id = pd.project_id
FROM analysis_source_types st, project_documents pd
WHERE st.id = a.source_type_id AND st.code = 'content' AND pd.content_id = a.source_id
  AND pd.is_active AND a.project_id IS NULL;

CREATE TABLE IF NOT EXISTS keywords (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    phrase character varying(200) NOT NULL,
    normalized_phrase character varying(200) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT keywords_pkey PRIMARY KEY (id),
    CONSTRAINT keywords_normalized_phrase_key UNIQUE (normalized_phrase),
    CONSTRAINT keywords_phrase_not_empty CHECK (btrim(phrase) <> ''),
    CONSTRAINT keywords_normalized_not_empty CHECK (btrim(normalized_phrase) <> '')
);

COMMENT ON TABLE keywords IS
    'عبارت کلیدی canonical؛ ذکر در متن خام در keyword_mentions است.';

CREATE TABLE IF NOT EXISTS keyword_mentions (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    keyword_id integer NOT NULL,
    analysis_id integer NOT NULL,
    source_type_id integer NOT NULL,
    source_id integer NOT NULL,
    project_id integer,
    created_by_user_id integer NOT NULL,
    mention_text character varying(300) NOT NULL DEFAULT '',
    start_offset integer,
    end_offset integer,
    confidence numeric(5, 4) NOT NULL DEFAULT 1,
    CONSTRAINT keyword_mentions_pkey PRIMARY KEY (id),
    CONSTRAINT keyword_mentions_keyword_id_fkey
        FOREIGN KEY (keyword_id) REFERENCES keywords(id) ON DELETE RESTRICT,
    CONSTRAINT keyword_mentions_analysis_id_fkey
        FOREIGN KEY (analysis_id) REFERENCES text_analyses(id) ON DELETE CASCADE,
    CONSTRAINT keyword_mentions_source_type_id_fkey
        FOREIGN KEY (source_type_id) REFERENCES analysis_source_types(id) ON DELETE RESTRICT,
    CONSTRAINT keyword_mentions_project_id_fkey
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT,
    CONSTRAINT keyword_mentions_created_by_user_id_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT keyword_mentions_source_id_check CHECK (source_id > 0),
    CONSTRAINT keyword_mentions_offsets_check
        CHECK (
            (start_offset IS NULL AND end_offset IS NULL)
            OR (start_offset >= 0 AND end_offset > start_offset)
        ),
    CONSTRAINT keyword_mentions_confidence_check
        CHECK (confidence >= 0 AND confidence <= 1)
);

COMMENT ON TABLE keyword_mentions IS
    'ذکر یک کلمهٔ کلیدی در متن خام گزارش/جلسه/پیام/محتوا؛ پروژه و صاحب متن جدا از تحلیل است.';

CREATE INDEX IF NOT EXISTS keyword_mentions_analysis_idx
    ON keyword_mentions (analysis_id);
CREATE INDEX IF NOT EXISTS keyword_mentions_keyword_idx
    ON keyword_mentions (keyword_id);
CREATE INDEX IF NOT EXISTS keyword_mentions_source_idx
    ON keyword_mentions (source_type_id, source_id);
CREATE INDEX IF NOT EXISTS keyword_mentions_project_idx
    ON keyword_mentions (project_id)
    WHERE project_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS keyword_mentions_user_idx
    ON keyword_mentions (created_by_user_id);

INSERT INTO keywords (phrase, normalized_phrase)
SELECT DISTINCT btrim(phrase), btrim(phrase)
FROM text_analysis_keywords
WHERE btrim(phrase) <> ''
ON CONFLICT (normalized_phrase) DO NOTHING;

INSERT INTO keyword_mentions (
    keyword_id, analysis_id, source_type_id, source_id,
    project_id, created_by_user_id, mention_text,
    start_offset, end_offset, confidence
)
SELECT
    k.id,
    tak.analysis_id,
    a.source_type_id,
    a.source_id,
    a.project_id,
    COALESCE(
        CASE st.code
            WHEN 'report' THEN r.created_by_user_id
            WHEN 'meeting' THEN mt.manager_user_id
            WHEN 'message' THEN m.sender_user_id
            WHEN 'content' THEN c.created_by_user_id
        END,
        a.created_by_user_id
    ),
    tak.mention_text,
    tak.start_offset,
    tak.end_offset,
    tak.confidence
FROM text_analysis_keywords tak
JOIN text_analyses a ON a.id = tak.analysis_id
JOIN analysis_source_types st ON st.id = a.source_type_id
JOIN keywords k ON k.normalized_phrase = btrim(tak.phrase)
LEFT JOIN reports r ON st.code = 'report' AND r.id = a.source_id
LEFT JOIN meetings mt ON st.code = 'meeting' AND mt.id = a.source_id
LEFT JOIN messages m ON st.code = 'message' AND m.id = a.source_id
LEFT JOIN contents c ON st.code = 'content' AND c.id = a.source_id
WHERE NOT EXISTS (
    SELECT 1 FROM keyword_mentions km WHERE km.analysis_id = tak.analysis_id
);

DROP TABLE IF EXISTS text_analysis_keywords;

COMMIT;
